javascript:
  image: oven/bun:alpine
  stage: test
  before_script:
    - 'bun install'
  script:
    - 'bun test --reporter=junit --reporter-outfile=./junit.xml --timeout 120000'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
